version: '3.4'
networks:
    network:
        driver: bridge
        ipam:
            config:
                -
                    subnet: 172.33.0.0/16
services:
    eth-net-intelligence-api.public.dappnode.eth:
        image: 'eth-net-intelligence-api.public.dappnode.eth:0.0.2'
        build:
            context: .
            dockerfile: ./build/Dockerfile
        container_name: eth-net-intelligence-api.public.dappnode.eth
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            network:
                ipv4_address: 172.33.2.19
        environment:
            - NODE_ENV=production
